# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repomonitorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
