# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
